### ISSUE TITLE
Terminal CD tests

### ISSUE THREAD

**Issue by L10N37** [JaCzekanski/ps1-tests#10]
I am pushing this across on the Orionsoft adapter, please note the other CD tests work.
This one is non responsive when connecting and sending commands over the serial adapter. (i.e. blank, help etc.)

**Comment by L10N37** [comment]
My bad, not an issue. The adapter only redirects the serial output and doesn't accept input.

**Comment by JaCzekanski** [comment]
@L10N37 Glad you have this resolved!
Can you share what's the goal for using this test? It's not really self-contained, I created it to experiment with CD driver.

**Comment by L10N37** [comment]
Capture samples with logic analyser, watch how SENS reacts to each command, use as a test suite, comparison to ODE/s

**Comment by ramapcsx2** [comment]
@L10N37 Note that xStation doesn't respond with all the proper SENSE signals as the real machine. It skips many situations where it makes no sense to behave like the real DSP. You'll learn which SENSE responses are actually necessary this way though. Good luck!

**Comment by L10N37** [comment]
Hi Rama, cheers. I'll probably end up hacking up a serial cable and wacking it on a Pico but no rush on this.

**Comment by L10N37** [comment]
Hacked an FT232 that I paid way too much for because i wanted it today and left my MCU drawer interstate, this works perfectly. I burnt an audio CD and used Termite 3.4 to connect, I am able to issue drive commands, play specific tracks, pause etc etc. Thanks

**Comment by L10N37** [comment]
Thought I'd mention

https://github.com/ABelliqueux/nolibgs_hello_worlds/blob/main/hello_cdda/hello_cdda.c

This plays audio FAR louder, I'm sure i will find out why eventually
